<?php
require_once 'core.php';
require 'vendor/autoload.php';

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\Fill;

if (isset($_GET['startDate']) && isset($_GET['endDate'])) {
    $startDate = $_GET['startDate'];
    $endDate = $_GET['endDate'];

    // Create new Spreadsheet object
    $spreadsheet = new Spreadsheet();
    $sheet = $spreadsheet->getActiveSheet();

    // Set document properties
    $spreadsheet->getProperties()
        ->setCreator('GPS Business System')
        ->setLastModifiedBy('GPS Business System')
        ->setTitle('GPS Profit Report')
        ->setSubject('GPS Profit Report ' . $startDate . ' to ' . $endDate)
        ->setDescription('GPS Profit Report generated by the system');

    // Style header row
    $headerStyle = [
        'font' => [
            'bold' => true,
            'color' => ['rgb' => 'FFFFFF'],
        ],
        'fill' => [
            'fillType' => Fill::FILL_SOLID,
            'startColor' => ['rgb' => '4472C4'],
        ],
        'borders' => [
            'allBorders' => [
                'borderStyle' => Border::BORDER_THIN,
            ],
        ],
        'alignment' => [
            'horizontal' => Alignment::HORIZONTAL_CENTER,
        ],
    ];

    // Add headers
    $sheet->setCellValue('A1', 'Date');
    $sheet->setCellValue('B1', 'Total Purchase');
    $sheet->setCellValue('C1', 'Total Sales');
    $sheet->setCellValue('D1', 'Total Credit');
    $sheet->setCellValue('E1', 'Total Expenses');
    $sheet->setCellValue('F1', 'Gross Profit');
    $sheet->setCellValue('G1', 'Net Profit');
    $sheet->setCellValue('H1', 'Comment');

    $sheet->getStyle('A1:H1')->applyFromArray($headerStyle);

    // Fetch data
    $sql = "SELECT 
                date,
                total_purchase,
                total_sales,
                total_credit,
                total_expenses,
                (total_sales - total_purchase) as gross_profit,
                (total_sales - total_purchase - total_expenses - total_credit) as net_profit,
                comment
            FROM gps_profit 
            WHERE date BETWEEN ? AND ?
            ORDER BY date DESC";

    $stmt = $connect->prepare($sql);
    $stmt->bind_param("ss", $startDate, $endDate);
    $stmt->execute();
    $result = $stmt->get_result();

    $row = 2;
    $totalPurchase = $totalSales = $totalCredit = $totalExpenses = $totalGrossProfit = $totalNetProfit = 0;

    while ($data = $result->fetch_assoc()) {
        $sheet->setCellValue('A' . $row, date('d-m-Y', strtotime($data['date'])));
        $sheet->setCellValue('B' . $row, $data['total_purchase']);
        $sheet->setCellValue('C' . $row, $data['total_sales']);
        $sheet->setCellValue('D' . $row, $data['total_credit']);
        $sheet->setCellValue('E' . $row, $data['total_expenses']);
        $sheet->setCellValue('F' . $row, $data['gross_profit']);
        $sheet->setCellValue('G' . $row, $data['net_profit']);
        $sheet->setCellValue('H' . $row, $data['comment']);

        // Update totals
        $totalPurchase += $data['total_purchase'];
        $totalSales += $data['total_sales'];
        $totalCredit += $data['total_credit'];
        $totalExpenses += $data['total_expenses'];
        $totalGrossProfit += $data['gross_profit'];
        $totalNetProfit += $data['net_profit'];

        $row++;
    }

    // Add totals row
    $totalRow = $row;
    $sheet->setCellValue('A' . $totalRow, 'TOTAL');
    $sheet->setCellValue('B' . $totalRow, $totalPurchase);
    $sheet->setCellValue('C' . $totalRow, $totalSales);
    $sheet->setCellValue('D' . $totalRow, $totalCredit);
    $sheet->setCellValue('E' . $totalRow, $totalExpenses);
    $sheet->setCellValue('F' . $totalRow, $totalGrossProfit);
    $sheet->setCellValue('G' . $totalRow, $totalNetProfit);

    // Style totals row
    $totalStyle = [
        'font' => ['bold' => true],
        'fill' => [
            'fillType' => Fill::FILL_SOLID,
            'startColor' => ['rgb' => 'E2EFDA'],
        ],
        'borders' => [
            'top' => ['borderStyle' => Border::BORDER_MEDIUM],
            'bottom' => ['borderStyle' => Border::BORDER_MEDIUM],
        ],
    ];
    $sheet->getStyle('A' . $totalRow . ':H' . $totalRow)->applyFromArray($totalStyle);

    // Auto-size columns
    foreach (range('A', 'H') as $col) {
        $sheet->getColumnDimension($col)->setAutoSize(true);
    }

    // Format number columns
    $numberFormat = '#,##0.00';
    $sheet->getStyle('B2:G' . $totalRow)->getNumberFormat()->setFormatCode($numberFormat);

    // Set content type and headers
    header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
    header('Content-Disposition: attachment;filename="GPS_Profit_Report_' . $startDate . '_to_' . $endDate . '.xlsx"');
    header('Cache-Control: max-age=0');

    // Save file
    $writer = new Xlsx($spreadsheet);
    $writer->save('php://output');
    exit;
} else {
    echo "Invalid request. Start date and end date are required.";
} 