<?php
require_once 'php_action/core.php';
require_once 'php_action/db_connect.php';
require_once 'php_action/telegram_bot_management.php';

// Check if user is logged in and has permission
if (!isset($_SESSION['userId'])) {
    die("Please log in first");
}

// Check for admin permission
$sql = "SELECT p.permission_name FROM permissions p 
        JOIN role_permissions rp ON p.permission_id = rp.permission_id
        JOIN users u ON u.role_id = rp.role_id
        WHERE u.user_id = ? AND p.permission_name = 'manage_telegram_bot'";

$stmt = $connect->prepare($sql);
$stmt->bind_param("i", $_SESSION['userId']);
$stmt->execute();
$result = $stmt->get_result();

if ($result->num_rows == 0) {
    die("You don't have permission to manage Telegram bot settings");
}

// Set page title and include header
$title = "Add Telegram Templates";
include 'includes/header.php';
?>

<div class="container-fluid" style="margin-top: 20px;">
    <div class="row">
        <div class="col-md-12">
            <ol class="breadcrumb">
                <li><a href="dashboard.php">Home</a></li>
                <li><a href="telegram_bot_settings.php">Telegram Bot Settings</a></li>
                <li class="active">Add Telegram Templates</li>
            </ol>

            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="page-heading"> <i class="glyphicon glyphicon-plus-sign"></i> Add Notification Templates</div>
                </div>
                <div class="panel-body">

<?php
// Define all the new templates we want to add
$templates = [
    // Digital Swap Templates
    [
        'name' => 'Digital Swap Created',
        'key' => 'digital_swap_created',
        'template' => 'New digital swap created by {{username}}. 
Amount: {{amount}} 
From: {{from_account}}
To: {{to_account}}
Reference: {{reference}}'
    ],
    [
        'name' => 'Digital Swap Approved',
        'key' => 'digital_swap_approved',
        'template' => 'Digital swap #{{swap_id}} has been approved by {{approver}}. 
Amount: {{amount}}
Time: {{approval_time}}'
    ],
    [
        'name' => 'Digital Swap Rejected',
        'key' => 'digital_swap_rejected',
        'template' => 'Digital swap #{{swap_id}} has been rejected by {{approver}}.
Reason: {{reason}}
Time: {{rejection_time}}'
    ],
    
    // Purchase Templates
    [
        'name' => 'New Purchase',
        'key' => 'new_purchase',
        'template' => 'New purchase #{{purchase_id}} has been created.
Supplier: {{supplier_name}}
Amount: {{amount}}
Items: {{item_count}}
Date: {{purchase_date}}'
    ],
    [
        'name' => 'Purchase Payment',
        'key' => 'purchase_payment',
        'template' => 'Payment of {{amount}} has been made for purchase #{{purchase_id}}.
Payment method: {{payment_method}}
Reference: {{reference}}
Balance due: {{balance}}'
    ],
    
    // Sales Templates
    [
        'name' => 'New Sale',
        'key' => 'new_sale',
        'template' => 'New sale #{{sale_id}} has been created.
Customer: {{customer_name}}
Amount: {{amount}}
Items: {{item_count}}
Date: {{sale_date}}'
    ],
    [
        'name' => 'Sale Payment Received',
        'key' => 'sale_payment_received',
        'template' => 'Payment of {{amount}} has been received for sale #{{sale_id}}.
Payment method: {{payment_method}}
Reference: {{reference}}
Balance due: {{balance}}'
    ],
    
    // Order Templates
    [
        'name' => 'Order Status Change',
        'key' => 'order_status_change',
        'template' => 'Order #{{order_id}} status has changed to "{{status}}".
Customer: {{customer_name}}
Updated by: {{updated_by}}
Time: {{update_time}}'
    ],
    [
        'name' => 'Order Shipped',
        'key' => 'order_shipped',
        'template' => 'Order #{{order_id}} has been shipped.
Customer: {{customer_name}}
Tracking: {{tracking_number}}
Courier: {{courier}}
Shipped by: {{shipped_by}}'
    ],
    
    // GPS Letter Templates
    [
        'name' => 'GPS Letter Generated',
        'key' => 'gps_letter_generated',
        'template' => 'GPS Letter #{{letter_id}} has been generated.
Type: {{letter_type}}
Recipient: {{recipient}}
Generated by: {{generated_by}}
Time: {{generation_time}}'
    ],
    [
        'name' => 'GPS Letter Sent',
        'key' => 'gps_letter_sent',
        'template' => 'GPS Letter #{{letter_id}} has been sent.
Type: {{letter_type}}
Recipient: {{recipient}}
Sent by: {{sent_by}}
Sent time: {{sent_time}}'
    ],
    
    // Quotation Templates
    [
        'name' => 'New Quotation',
        'key' => 'new_quotation',
        'template' => 'New quotation #{{quotation_id}} has been created.
Customer: {{customer_name}}
Amount: {{amount}}
Valid until: {{valid_until}}
Created by: {{created_by}}'
    ],
    [
        'name' => 'Quotation Accepted',
        'key' => 'quotation_accepted',
        'template' => 'Quotation #{{quotation_id}} has been accepted by customer.
Customer: {{customer_name}}
Amount: {{amount}}
Accepted on: {{acceptance_date}}
Converted to Order: {{order_id}}'
    ],
    
    // Production Templates
    [
        'name' => 'Production Order Created',
        'key' => 'production_order_created',
        'template' => 'New production order #{{prod_order_id}} has been created.
Product: {{product_name}}
Quantity: {{quantity}}
Target date: {{target_date}}
Created by: {{created_by}}'
    ],
    [
        'name' => 'Raw Material Purchase',
        'key' => 'raw_material_purchase',
        'template' => 'Raw materials purchased for production.
Purchase ID: {{purchase_id}}
Materials: {{materials_list}}
Amount: {{amount}}
Supplier: {{supplier}}
Date: {{purchase_date}}'
    ],
    [
        'name' => 'Production Completed',
        'key' => 'production_completed',
        'template' => 'Production order #{{prod_order_id}} has been completed.
Product: {{product_name}}
Quantity produced: {{quantity}}
Completion date: {{completion_date}}
Quality check: {{quality_status}}'
    ],
    
    // POS Templates
    [
        'name' => 'POS Sale',
        'key' => 'pos_sale',
        'template' => 'New POS sale #{{sale_id}} has been recorded.
Amount: {{amount}}
Payment method: {{payment_method}}
Cashier: {{cashier}}
Time: {{sale_time}}'
    ],
    [
        'name' => 'POS Cash Drawer',
        'key' => 'pos_cash_drawer',
        'template' => 'Cash drawer {{action}} by {{user}}.
Starting amount: {{starting_amount}}
Ending amount: {{ending_amount}}
Time: {{action_time}}'
    ],
    
    // Session Templates
    [
        'name' => 'User Login',
        'key' => 'user_login',
        'template' => 'User {{username}} logged in.
IP: {{ip_address}}
Device: {{device}}
Time: {{login_time}}'
    ],
    [
        'name' => 'Login Failed Attempt',
        'key' => 'login_failed',
        'template' => 'Failed login attempt for user {{username}}.
IP: {{ip_address}}
Device: {{device}}
Time: {{attempt_time}}
Attempt count: {{attempt_count}}'
    ],
    [
        'name' => 'Active Session Management',
        'key' => 'session_management',
        'template' => 'Session for {{username}} has been {{action}} by {{admin}}.
IP: {{ip_address}}
Session start: {{session_start}}
Action time: {{action_time}}'
    ],
    
    // Report Templates
    [
        'name' => 'Report Generated',
        'key' => 'report_generated',
        'template' => 'Report "{{report_name}}" has been generated by {{username}}.
Period: {{report_period}}
Time: {{generation_time}}'
    ],
    [
        'name' => 'Financial Report Alert',
        'key' => 'financial_report_alert',
        'template' => '⚠️ Financial Alert ⚠️
Type: {{alert_type}}
Details: {{alert_details}}
Report: {{report_name}}
Generated by: {{username}}
Time: {{alert_time}}'
    ],
    
    // Email Templates
    [
        'name' => 'Email Sent',
        'key' => 'email_sent',
        'template' => 'Email sent to {{recipient}}.
Subject: {{subject}}
Sent by: {{sent_by}}
Time: {{sent_time}}'
    ],
    [
        'name' => 'Email Campaign',
        'key' => 'email_campaign',
        'template' => 'Email campaign "{{campaign_name}}" has been sent.
Recipients: {{recipient_count}}
Open rate: {{open_rate}}%
Click rate: {{click_rate}}%
Time: {{sent_time}}'
    ],
    [
        'name' => 'Email Error',
        'key' => 'email_error',
        'template' => 'Error sending email to {{recipient}}.
Subject: {{subject}}
Error: {{error_message}}
Time: {{error_time}}'
    ]
];

// Track results
$inserted = 0;
$skipped = 0;
$errors = [];
$success = [];

// Insert each template
foreach ($templates as $template) {
    // Check if the template key already exists
    $sql = "SELECT id FROM telegram_notification_templates WHERE template_key = ?";
    $stmt = $connect->prepare($sql);
    $stmt->bind_param("s", $template['key']);
    $stmt->execute();
    $result = $stmt->get_result();
    
    if ($result && $result->num_rows > 0) {
        $skipped++;
        $errors[] = "Template key '{$template['key']}' already exists";
        continue;
    }
    
    // Create the template
    $result = createNotificationTemplate($template['name'], $template['key'], $template['template']);
    
    if ($result['success']) {
        $inserted++;
        $success[] = "Successfully added template: {$template['name']}";
    } else {
        $errors[] = "Failed to create template '{$template['name']}': " . $result['message'];
    }
}
?>

                    <div class="alert alert-info">
                        <h4><i class="glyphicon glyphicon-info-sign"></i> Template Creation Summary</h4>
                        <p>Successfully inserted: <strong><?php echo $inserted; ?></strong> templates</p>
                        <p>Skipped (already existing): <strong><?php echo $skipped; ?></strong> templates</p>
                    </div>

                    <?php if (!empty($success)): ?>
                    <div class="panel panel-success">
                        <div class="panel-heading">
                            <h3 class="panel-title"><i class="glyphicon glyphicon-ok-circle"></i> Successfully Added Templates</h3>
                        </div>
                        <div class="panel-body">
                            <ul class="list-group">
                                <?php foreach ($success as $msg): ?>
                                <li class="list-group-item"><i class="glyphicon glyphicon-ok text-success"></i> <?php echo $msg; ?></li>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                    </div>
                    <?php endif; ?>

                    <?php if (!empty($errors)): ?>
                    <div class="panel panel-warning">
                        <div class="panel-heading">
                            <h3 class="panel-title"><i class="glyphicon glyphicon-exclamation-sign"></i> Skipped Templates</h3>
                        </div>
                        <div class="panel-body">
                            <ul class="list-group">
                                <?php foreach ($errors as $error): ?>
                                <li class="list-group-item"><i class="glyphicon glyphicon-info-sign text-warning"></i> <?php echo $error; ?></li>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                    </div>
                    <?php endif; ?>

                    <div class="text-center">
                        <a href="telegram_bot_settings.php" class="btn btn-primary btn-lg">
                            <i class="glyphicon glyphicon-arrow-left"></i> Return to Telegram Bot Settings
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<?php include 'includes/footer.php'; ?> 