<?php
require_once 'core.php';

$valid['success'] = array('success' => false, 'messages' => array(), 'html' => '');

if($_POST) {
    $startDate = $_POST['startDate'];
    $endDate = $_POST['endDate'];
    $supplier = isset($_POST['supplier']) ? $_POST['supplier'] : '';

    $sql = "SELECT p.*, s.company_name, s.contact_person, s.phone 
            FROM purchases p 
            LEFT JOIN suppliers s ON p.supplier_id = s.id 
            WHERE p.active = 1 ";

    if($startDate && $endDate) {
        $startDate = date('Y-m-d', strtotime($startDate));
        $endDate = date('Y-m-d', strtotime($endDate));
        $sql .= " AND p.purchase_date BETWEEN '$startDate' AND '$endDate'";
    }
    if($supplier) {
        $sql .= " AND p.supplier_id = '$supplier'";
    }
    
    $sql .= " ORDER BY p.purchase_date DESC";
    
    $query = $connect->query($sql);
    
    if(!$query) {
        $valid['success'] = false;
        $valid['messages'] = "Database error: " . $connect->error;
        echo json_encode($valid);
        exit();
    }
    
    $count = $query->num_rows;

    if($count > 0) {
        $table = '
        <div class="report-container">
            <div class="report-header">
                <div class="company-info">
                    <h2>Purchase Report</h2>
                    <p>Period: ' . date('d M Y', strtotime($startDate)) . ' - ' . date('d M Y', strtotime($endDate)) . '</p>
                    ' . ($supplier ? '<p>Supplier: ' . getSupplierName($connect, $supplier) . '</p>' : '<p>All Suppliers</p>') . '
                </div>
            </div>

            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>Date</th>
                        <th>Purchase #</th>
                        <th>Supplier</th>
                        <th>Contact</th>
                        <th>Items</th>
                        <th>Sub Total</th>
                        <th>VAT (15%)</th>
                        <th>Total Amount</th>
                    </tr>
                </thead>
                <tbody>';

        $totalAmount = 0;
        while($result = $query->fetch_array()) {
            $purchaseId = $result['id'];
            $items = getPurchaseItems($connect, $purchaseId);
            
            $table .= '
                <tr>
                    <td>' . date('d M Y', strtotime($result['purchase_date'])) . '</td>
                    <td>' . $result['purchase_number'] . '</td>
                    <td>' . $result['company_name'] . '</td>
                    <td>' . $result['contact_person'] . '<br>' . $result['phone'] . '</td>
                    <td>' . $items . '</td>
                    <td style="text-align:right;">' . number_format($result['sub_total'], 2) . '</td>
                    <td style="text-align:right;">' . number_format($result['vat'], 2) . '</td>
                    <td style="text-align:right;">' . number_format($result['grand_total'], 2) . '</td>
                </tr>';
            
            $totalAmount += $result['grand_total'];
        }

        $table .= '
                </tbody>
                <tfoot>
                    <tr>
                        <th colspan="7" style="text-align:right;">Total Amount</th>
                        <th style="text-align:right;">' . number_format($totalAmount, 2) . ' ETB</th>
                    </tr>
                </tfoot>
            </table>
            
            <div style="margin-top: 20px;">
                <p><strong>Report Generated:</strong> ' . date('d M Y H:i:s') . '</p>
                <p><strong>Generated By:</strong> ' . (isset($_SESSION['userName']) ? $_SESSION['userName'] : 'System') . '</p>
            </div>
        </div>';

        $valid['success'] = true;
        $valid['messages'] = "Report generated successfully";
        $valid['html'] = $table;

    } else {
        $table = '
        <div class="no-purchases-message">
            <i class="glyphicon glyphicon-info-sign"></i>
            No purchases found for the selected period
        </div>';

        $valid['success'] = true;
        $valid['messages'] = "No purchases found";
        $valid['html'] = $table;
    }

} else {
    $valid['success'] = false;
    $valid['messages'] = "Invalid request";
}

$connect->close();

echo json_encode($valid);

// Helper function to get supplier name
function getSupplierName($connect, $supplierId) {
    $sql = "SELECT company_name FROM suppliers WHERE id = '$supplierId'";
    $result = $connect->query($sql);
    if($result->num_rows > 0) {
        return $result->fetch_array()['company_name'];
    }
    return 'Unknown Supplier';
}

// Helper function to get purchase items
function getPurchaseItems($connect, $purchaseId) {
    $sql = "SELECT pi.*, p.name 
            FROM purchase_items pi
            LEFT JOIN products p ON pi.product_id = p.product_id
            WHERE pi.purchase_id = '$purchaseId'";
    $result = $connect->query($sql);
    
    $items = array();
    while($row = $result->fetch_array()) {
        $items[] = $row['name'] . ' (' . $row['quantity'] . ' units)';
    }
    
    return implode('<br>', $items);
}
?> 