<?php
require_once 'core.php';
require '../vendor/autoload.php'; // For PHPMailer

use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

$valid['success'] = array('success' => false, 'messages' => array());

if($_POST) {
    $startDate = $_POST['startDate'];
    $endDate = $_POST['endDate'];
    $supplier = isset($_POST['supplier']) ? $_POST['supplier'] : '';
    $email = $_POST['email'];

    // Validate email
    if(!filter_var($email, FILTER_VALIDATE_EMAIL)) {
        $valid['success'] = false;
        $valid['messages'] = "Invalid email address";
        echo json_encode($valid);
        exit();
    }

    // Generate report content
    $sql = "SELECT p.*, s.company_name, s.contact_person, s.phone 
            FROM purchases p 
            LEFT JOIN suppliers s ON p.supplier_id = s.id 
            WHERE p.active = 1 ";

    if($startDate && $endDate) {
        $startDate = date('Y-m-d', strtotime($startDate));
        $endDate = date('Y-m-d', strtotime($endDate));
        $sql .= " AND p.purchase_date BETWEEN '$startDate' AND '$endDate'";
    }
    if($supplier) {
        $sql .= " AND p.supplier_id = '$supplier'";
    }
    
    $sql .= " ORDER BY p.purchase_date DESC";

    $query = $connect->query($sql);
    if(!$query) {
        $valid['success'] = false;
        $valid['messages'] = "Database error: " . $connect->error;
        echo json_encode($valid);
        exit();
    }

    $count = $query->num_rows;

    if($count > 0) {
        // Start building email content
        $emailContent = '
        <style>
            table { border-collapse: collapse; width: 100%; margin-bottom: 20px; }
            th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
            th { background-color: #f5f5f5; }
            .total-row { font-weight: bold; }
            .text-right { text-align: right; }
            .report-header { margin-bottom: 20px; }
            .company-info { margin-bottom: 20px; }
        </style>
        
        <div class="report-container">
            <div class="report-header">
                <div class="company-info">
                    <h2>Purchase Report</h2>
                    <p>Period: ' . date('d M Y', strtotime($startDate)) . ' - ' . date('d M Y', strtotime($endDate)) . '</p>
                    ' . ($supplier ? '<p>Supplier: ' . getSupplierName($connect, $supplier) . '</p>' : '<p>All Suppliers</p>') . '
                </div>
            </div>
            
            <table>
                <thead>
                    <tr>
                        <th>Date</th>
                        <th>Purchase #</th>
                        <th>Supplier</th>
                        <th>Items</th>
                        <th>Sub Total</th>
                        <th>VAT (15%)</th>
                        <th>Total Amount</th>
                    </tr>
                </thead>
                <tbody>';

        $totalAmount = 0;
        while($result = $query->fetch_array()) {
            $purchaseId = $result['id'];
            $items = getPurchaseItems($connect, $purchaseId);
            
            $emailContent .= '
                <tr>
                    <td>' . date('d M Y', strtotime($result['purchase_date'])) . '</td>
                    <td>' . $result['purchase_number'] . '</td>
                    <td>' . $result['company_name'] . '</td>
                    <td>' . $items . '</td>
                    <td class="text-right">' . number_format($result['sub_total'], 2) . '</td>
                    <td class="text-right">' . number_format($result['vat'], 2) . '</td>
                    <td class="text-right">' . number_format($result['grand_total'], 2) . '</td>
                </tr>';
            
            $totalAmount += $result['grand_total'];
        }

        $emailContent .= '
                </tbody>
                <tfoot>
                    <tr class="total-row">
                        <td colspan="6" class="text-right">Total Amount</td>
                        <td class="text-right">' . number_format($totalAmount, 2) . ' ETB</td>
                    </tr>
                </tfoot>
            </table>
            
            <div style="margin-top: 20px;">
                <p><strong>Report Generated:</strong> ' . date('d M Y H:i:s') . '</p>
                <p><strong>Generated By:</strong> ' . (isset($_SESSION['userName']) ? $_SESSION['userName'] : 'System') . '</p>
            </div>
        </div>';

        try {
            $mail = new PHPMailer(true);
            
            // Server settings
            $mail->SMTPDebug = 0;  // Disable debug output
            $mail->isSMTP();
            $mail->Host = 'mail.lebawi.net';
            $mail->SMTPAuth = true;
            $mail->Username = 'swapcapital@lebawi.net';
            $mail->Password = 'swapcapital@0924';
            $mail->SMTPSecure = PHPMailer::ENCRYPTION_SMTPS; // Use SMTPS for port 465
            $mail->Port = 465;

            // Recipients
            $mail->setFrom('swapcapital@lebawi.net', 'Lebawi Net Trading PLC');
            $mail->addAddress($email);

            // Content
            $mail->isHTML(true);
            $mail->Subject = 'Purchase Report (' . date('d M Y', strtotime($startDate)) . ' - ' . date('d M Y', strtotime($endDate)) . ')';
            $mail->Body = $emailContent;
            $mail->AltBody = 'Please view this email in an HTML-compatible email client to see the purchase report.';

            $mail->send();

            $valid['success'] = true;
            $valid['messages'] = 'Report has been sent successfully to ' . $email;

        } catch (Exception $e) {
            $valid['success'] = false;
            $valid['messages'] = 'Error sending email: ' . $mail->ErrorInfo;
            $valid['error_details'] = $e->getMessage();
        }

    } else {
        $valid['success'] = false;
        $valid['messages'] = 'No purchase data found for the selected period';
    }

} else {
    $valid['success'] = false;
    $valid['messages'] = 'Invalid request';
}

$connect->close();

echo json_encode($valid);

// Helper function to get supplier name
function getSupplierName($connect, $supplierId) {
    $sql = "SELECT company_name FROM suppliers WHERE id = '$supplierId'";
    $result = $connect->query($sql);
    if($result->num_rows > 0) {
        return $result->fetch_array()['company_name'];
    }
    return 'Unknown Supplier';
}

// Helper function to get purchase items
function getPurchaseItems($connect, $purchaseId) {
    $sql = "SELECT pi.*, p.name 
            FROM purchase_items pi
            LEFT JOIN products p ON pi.product_id = p.product_id
            WHERE pi.purchase_id = '$purchaseId'";
    $result = $connect->query($sql);
    
    $items = array();
    while($row = $result->fetch_array()) {
        $items[] = $row['name'] . ' (' . $row['quantity'] . ' units)';
    }
    
    return implode(', ', $items);
}
?> 